version: 2
updates:
  # Enable version updates for Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "valkey-io/php-maintainers"
    assignees:
      - "valkey-io/php-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "valkey-io/php-maintainers"
    assignees:
      - "valkey-io/php-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
